import Head from "next/head";
import Link from "next/link";
import { Button, Input, Carousel, Form, Divider } from "antd";
import * as AiIcons from "react-icons/ai";

export default function Home() {
  function onChange(a, b, c) {
    console.log(a, b, c);
  }

  const onFinish = (values) => {
    console.log("Success:", values);
  };

  const onFinishFailed = (errorInfo) => {
    console.log("Failed:", errorInfo);
  };

  return (
    <div>
      <Head>
        <title>Academe</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Carousel afterChange={onChange} className="carousel-full">
        <div className="carousel-item">
          <div className="carousel-item-content">
            <div className="login-header">
              <h2 className="white-text">Academe</h2>
              <p className="light-grey-text">Learn, Excel, Lead!</p>
            </div>
            <div className="login-form">
              <div className="login-content">
                <Divider>Learner Login</Divider>
                <Form
                  layout="vertical"
                  className="form"
                  name="learner-form"
                  initialValues={{ remember: true }}
                  onFinish={onFinish}
                  onFinishFailed={onFinishFailed}
                >
                  <Form.Item
                    name={"learner-email"}
                    label="Email"
                    rules={[
                      {
                        required: true,
                        message: "Please input your Email",
                        type: "email",
                      },
                    ]}
                  >
                    <Input
                      prefix={
                        <AiIcons.AiOutlineUser className="site-form-item-icon" />
                      }
                    />
                  </Form.Item>
                  <Form.Item
                    label="Password"
                    name="learner-password"
                    rules={[
                      {
                        required: true,
                        message: "Please input your password!",
                      },
                    ]}
                  >
                    <Input.Password
                      prefix={
                        <AiIcons.AiOutlineLock className="site-form-item-icon" />
                      }
                    />
                  </Form.Item>

                  <Form.Item>
                    <Button type="primary" htmlType="submit" block>
                      Login
                    </Button>
                  </Form.Item>
                  <Form.Item className="center-text">
                    Or <span className="link small-text">Activate Account</span>
                  </Form.Item>
                </Form>
              </div>
            </div>
          </div>
        </div>
        <div className="carousel-item">
          <div className="carousel-item-content">
            <div className="login-header">
              <h2 className="white-text">Academe</h2>
              <p className="light-grey-text">Learn, Excel, Lead!</p>
            </div>
            <div className="login-form">
              <div className="login-content">
                <Divider>Educator Login</Divider>
                <Form
                  name="educator-form"
                  layout="vertical"
                  className="form"
                  initialValues={{ remember: true }}
                  onFinish={onFinish}
                  onFinishFailed={onFinishFailed}
                >
                  <Form.Item
                    name={"educator-email"}
                    label="Email"
                    rules={[
                      {
                        required: true,
                        message: "Please input your Email",
                        type: "email",
                      },
                    ]}
                  >
                    <Input
                      prefix={
                        <AiIcons.AiOutlineUser className="site-form-item-icon" />
                      }
                    />
                  </Form.Item>
                  <Form.Item
                    label="Password"
                    name="educator-password"
                    rules={[
                      {
                        required: true,
                        message: "Please input your password!",
                      },
                    ]}
                  >
                    <Input.Password
                      prefix={
                        <AiIcons.AiOutlineLock className="site-form-item-icon" />
                      }
                    />
                  </Form.Item>

                  <Form.Item>
                    <Link href="/teacher/" passHref={true}>
                      <Button type="primary" htmlType="submit" block>
                        Login
                      </Button>
                    </Link>
                  </Form.Item>
                </Form>
              </div>
            </div>
          </div>
        </div>
        <div className="carousel-item">
          <div className="carousel-item-content">
            <div className="login-header">
              <h2 className="white-text">Academe</h2>
              <p className="light-grey-text">Learn, Excel, Lead!</p>
            </div>
            <div className="login-form">
              <div className="login-content">
                <Divider>Admin Login</Divider>
                <Form
                  layout="vertical"
                  className="form"
                  name="admin-form"
                  initialValues={{ remember: true }}
                  onFinish={onFinish}
                  onFinishFailed={onFinishFailed}
                >
                  <Form.Item
                    name={"admin-email"}
                    label="Email"
                    rules={[
                      {
                        required: true,
                        message: "Please input your Email",
                        type: "email",
                      },
                    ]}
                  >
                    <Input
                      prefix={
                        <AiIcons.AiOutlineUser className="site-form-item-icon" />
                      }
                    />
                  </Form.Item>
                  <Form.Item
                    label="Password"
                    name="admin-password"
                    rules={[
                      {
                        required: true,
                        message: "Please input your password!",
                      },
                    ]}
                  >
                    <Input.Password
                      prefix={
                        <AiIcons.AiOutlineLock className="site-form-item-icon" />
                      }
                    />
                  </Form.Item>

                  <Form.Item>
                    <Link href="/admin/" passHref={true}>
                      <Button type="primary" htmlType="submit" block>
                        Login
                      </Button>
                    </Link>
                  </Form.Item>
                </Form>
              </div>
            </div>
          </div>
        </div>
      </Carousel>
    </div>
  );
}
